### ISSUE TITLE
Document all modules in TelestionGroup/telestion-docs

### ISSUE THREAD

**Issue by cb0s** [wuespace/telestion-core#103]
We will have to document all our available Verticles and "modules" TelestionGroup/telestion-docs.
I will have to document #31 but I am not really eager to document everything alone. 🤣

**Comment by cb0s** [comment]
Everybody documents his/her own contributions. This is high priority now.

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. outdated
2. unspecific: there is no information on what's missing
3. inactivity after the "needs info" tag got added
