### ISSUE TITLE
Link MAVLink-Adapter with its designated logger

### ISSUE THREAD

**Issue by cb0s** [wuespace/telestion-core#109]
The MAVLink-Adapter must be connected to @oanamateiflorin's logger.

For this we have 2 scenario:

- Message-Parsing is successful
- Message-Parsing is not successful

My suggestion is the following:

- if everything runs smoothly we simply add the logger in-Address to the publishing addresses of the parser and pass the Mavlink-Message json-encoded (we don't need the header in the logs do we? If we do I can arrange that this is not a problem 😄 )
- if an error occurs we catch them at one point and the logger receives a RawPackage with basically nothing but the raw payload bytes (header is obviously part)

**Comment by jvpichowski** [comment]
Since we switched to a generic logging framework and you started to redesign the MAVLink-Adapter it is time to close this, or not?

**Comment by cb0s** [comment]
I wanted to close this with Mavlink V2 to ensure this is really integrated.
Let's link it to the right PR though :)

**Comment by cb0s** [comment]
Closed with the release of v0.2.0 of [telestion-extension-mavlink](https://github.com/wuespace/telestion-extension-mavlink)
