### ISSUE TITLE
Add timestamp for creation time to JsonMessage

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#121]
See #120

**Comment by cb0s** [comment]
Still relevant?

**Comment by jvpichowski** [comment]
Yes, it is relevant for the next iteration. But we need to discuss the right approach first.

**Comment by pklaschka** [comment]
Closing this as it is based on outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. this probably fits better into the `HeaderInformation`
2. `JsonMessage` also got used for configuration objects and thus renamed to `JsonRecord`. I don't feel like this is fits into the `JsonRecord` on a domain level
3. enforcing this would add a lot of overhead for distributed systems (including both clients and also horzontally scaled, distributed microservice architectures) to ensure time synchronization
