### ISSUE TITLE
Build raspberry server image 

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#243]

**Comment by fussel178** [comment]
I think, it's better to use the Docker containers published by the projects and an Ubuntu Core image or something else?

**Comment by pklaschka** [comment]
Closing this as it is based on outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. inactivity without a clearly documented need
2. successful implementation with Docker doesn't "force" this
3. no clear use-case
