### ISSUE TITLE
Spring Cleaning

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#258]
- [x] Delete old packages @pklaschka 
- [x] Delete old releases @pklaschka 
- [x] Find a better way to list contributors in Readme @pklaschka 
- [x] Change About Url @pklaschka 
- [x] Clean up dependencies
- [x] Seperate Mavlink to `telestion-extension-mavlink` @cb0s 
- [x] Clean PRs @jvpichowski 
- [x] Rework Release Workflow @fussel178 
- [x] Rework default config @jvpichowski 
- [ ] #488
- [ ] #489
- [x] Setup Telestion repo to bundle others @fussel178 (done for telestion-project-daedalus2)
- [x] Implement conventional commit naming rules @fussel178 
- [x] implement telestion-project detection in Client CLI @pklaschka

**Comment by pklaschka** [comment]
>  Find a better way to list contributors in Readme @pklaschka

Please define "better" 😉.

**Comment by cb0s** [comment]
@jvpichowski is this still in progress or can we at least unpin this issue?

**Comment by fussel178** [comment]
Converted both pending steps to issues for separate tracking.
A big thank you to all contributors for your time. :wink:
