### ISSUE TITLE
Java Packaging

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#301]
@fussel178 

Edit: It is already here:
https://jfrog.com/blog/java-artifacts-just-got-better-jpackage-is-production-ready-in-java-16-2/

There will be nice options in the near future to explore:

* https://openjdk.java.net/jeps/275
* https://openjdk.java.net/jeps/343
* https://www.infoq.com/news/2019/03/jep-343-jpackage/

**Comment by jvpichowski** [comment]
Next steps: Define outcome.

**Comment by jvpichowski** [comment]
Tool uasage: https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html

**Comment by jvpichowski** [comment]
See serial-connectors

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. missing use-case description / information on advantages over other methods
2. inactivity
