### ISSUE TITLE
Create a Pre-Release 1.0

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#311]
Creating the first Release is a tough part. In most cases there is a mental blockade because you want to ship the best possible product with the first version, making it never happen. We aim at a pre-release to give us some mental freedom to fix things afterward.

- [ ] Identify tasks to be done (keep them small we go for a minimum viable product)
- [ ] estimate the needed time
- [ ] execute tasks
- [ ] release
- [ ] write a blog entry

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. inactivity
2. not actionable
3. not necessarily aligned with current plans
