### ISSUE TITLE
Runtime Configuration

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#318]
We need some sort of "dynamic configuration reloading" when the application is already running.

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. unclear use-case: why do we need this? What advantages does it bring?
2. inactivity
3. might be solved "automatically" / "accidentally" with the current launch process rewrite and needs to be re-evaluated afterwards
