### ISSUE TITLE
Json-Schema based message definitions

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#319]

**Comment by jvpichowski** [comment]
Powerful alien technology: https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-json

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. inactivity
2. no clear use-case / advantages / scope description
3. JSON schema probably shouldn't be the language to write things in, but should be generated from some other language (e.g., https://wuespace.github.io/telestion-message-type-dsl-specs/#)
