### ISSUE TITLE
Author javadoc tag

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#33]
We should add the author tag to the javadoc to keep track who could help in case of questions and because it is a good practice.

**Comment by jvpichowski** [comment]
Did you check the files? If yes, you could close it.

**Comment by cb0s** [comment]
I noticed that for external developers it might be difficult to identify us by our names. What do you think of the idea that in brackets after the name, we add the GH-Name with a trailing '@' (e.g. `Cedric Boes (@cb0s)`)?
