### ISSUE TITLE
telestion-updater

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion-core#4]

**Comment by cb0s** [comment]
Can this be closed?

**Comment by jvpichowski** [comment]
No, it still needs to be implemented. I will tackle this down together with Philipp.

**Comment by fussel178** [comment]
Is this still valid?

**Comment by pklaschka** [comment]
Closing this as it is based on potentially outdated assumptions. Please feel free to re-open (with an updated description) based on the current structure.

## Considerations for closing this
1. inactivity
2. missing description / use-case / ...
